# Generated by Django 5.2.1 on 2025-05-26 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_background",
            field=models.ImageField(
                blank=True,
                help_text="Profile background of user.",
                null=True,
                upload_to="images/profile_backgrounds",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                help_text="Profile picture of user.",
                null=True,
                upload_to="images/profile_pictures",
            ),
        ),
    ]
