# Generated by Django 5.2.1 on 2025-05-26 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_profile_background_user_profile_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                blank=True, default="user", help_text="Role of user."
            ),
        ),
    ]
