# Generated by Django 5.2.1 on 2025-05-28 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[("host", "Host"), ("user", "User")],
                default="user",
                help_text="Role of user.",
            ),
        ),
    ]
