# Generated by Django 5.2.1 on 2025-05-27 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hackathons", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="hackathon",
            name="hosted_by",
            field=models.ForeignKey(
                default=1,
                help_text="The user who hosted this hackathon.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hosted_hackathons",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
