# Generated by Django 5.2.1 on 2025-05-27 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hackathons", "0002_hackathon_hosted_by"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="participant",
            name="hackathon",
            field=models.ForeignKey(
                help_text="Hackathon the user has applied to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="participants",
                to="hackathons.hackathon",
            ),
        ),
        migrations.AlterField(
            model_name="participant",
            name="user",
            field=models.ForeignKey(
                help_text="User who applied to participate in the hackathon.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hackathons",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
