# Generated by Django 5.2.1 on 2025-05-28 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hackathons", "0003_alter_participant_hackathon_alter_participant_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Categories"},
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(
                blank=True, help_text="Slug of category.", unique=True
            ),
        ),
    ]
