# Generated by Django 5.2.1 on 2025-05-28 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hackathons", "0004_alter_category_options_alter_category_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="participant",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("active", "Active"),
                    ("pending", "Pending"),
                    ("rejected", "Rejected"),
                    ("completed", "Completed"),
                ],
                default="pending",
                help_text="Current participation status of the user in the hackathon.",
            ),
        ),
    ]
